### PR TITLE
metrics-redis-graphite.rb: skip invalid keys

### PR DESCRIPTION
**Pull request by boutetnico**
## Pull Request Checklist

Is this in reference to an existing issue? No

#### General

- [ ] Update Changelog following the conventions laid out on [Our CHANGELOG Guidelines ](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### Purpose

Using Redis 4.0, several keys were added in statistics. This PR updates the list of skip keys. It should not break any backward compatibility as the lines removed could not be parsed by Carbon receiver and produced the following warnings:

```
Feb  1 16:22:20 sensu01 carbon-cache.py[480]: 01/02/2019 16:22:20 :: [listener] invalid line received from client 127.0.0.1:52802, ignoring [redis01.redis.atomicvar_api atomic-builtin 1549038140]
Feb  1 16:22:20 sensu01 carbon-cache.py[480]: 01/02/2019 16:22:20 :: [listener] invalid line received from client 127.0.0.1:52802, ignoring [redis01.redis.used_memory_peak_perc 71.11% 1549038140]
Feb  1 16:22:20 sensu01 carbon-cache.py[480]: 01/02/2019 16:22:20 :: [listener] invalid line received from client 127.0.0.1:52802, ignoring [redis01.redis.used_memory_dataset_perc 91.30% 1549038140]
Feb  1 16:22:20 sensu01 carbon-cache.py[480]: 01/02/2019 16:22:20 :: [listener] invalid line received from client 127.0.0.1:52802, ignoring [redis01.redis.master_replid 05da6744ccac06bbb85b2627a6042182c3d17152 1549038140]
```

These lines 

#### Known Compatibility Issues

None

### CODE REVIEW

**Comment by majormoses** [comment]
Is this something specific to new versions or were these always an issue no one reported? Just trying to understand so I can determine how to write up the changelog.

**Comment by boutetnico** [comment]
@majormoses it's specific to new Redis version. The plugin was written for an older Redis version but was not updated since that time to exclude the non-numeric keys from its output that were added in Redis 4.0.
For reference, the keys I remove in this PR are not present in the stats output of Redis 3.2.6.

**Comment by majormoses** [comment]
I need to either go disable the tests or fix the test cootraping as its broken. Hopefully I will try to find some time this weekend.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-redis/versions/3.1.0

**Comment by boutetnico** [comment]
@majormoses I just realised I removed an extra key that should have stayed :/. I opened a PR to fix this https://github.com/sensu-plugins/sensu-plugins-redis/pull/68.

**Pull request merged**
