### PR TITLE
set critical exit status as default on failures

### LINKED ISSUE #3: Exit status on failure
I would like to use such sensu plugins to monitor our redis server, but I have faced with issue on rescue exit status. When check cannot connect on redis server it return different exit status, here is a list:
- check-redis-info.rb - warning
- check-redis-list-length.rb - unknown
- check-redis-memory.rb - configurable (warn/critical)
- check-redis-ping.rb - warning
- check-redis-slave-status.rb - critical

So I suppose we should to lead to one species all redis checks. According to nagios guildlines (https://nagios-plugins.org/doc/guidelines.html#AEN78) we should use critical exit status for such failures. Also It will be good to make them configurable (like in check-redis-memory.rb check).

So here is my suggestion/summary:
- Default behavior is critical
- Add param to change it to warning
- And of course these changes break compatibility with old version :(

### PR DESCRIPTION
**Pull request by kam1kaze**
It is my vision to fix #3

### CODE REVIEW

**Comment by mattyjones** [comment]
@kam1kaze Can you please update the CHANGELOG with these changes as well and then we can merge this in.

Thanks

**Comment by kam1kaze** [comment]
I have updated the changelog

**Comment by mattyjones** [comment]
@kam1kaze  Can you try a rebase so that this will merge clean.

Thanks!

**Comment by mattyjones** [comment]
@kam1kaze  bump

**Comment by kam1kaze** [comment]
I completely forgot about such pull request. I have rebased it :)

**Comment by analytically** [comment]
Again, we should have some guidelines here. Some plugins use unknown when they're unable to connect. Also this should not be behind a flag, but default behaviour.

**Comment by mattyjones** [comment]
@analytically  @kam1kaze  My thoughts on unknown are that is could be used for a configuration error or anything of that nature.

**Comment by majormoses** [comment]
@mattyjones I tend to find that when you have plugins that are use case specific such as `check-redis-list-length.rb` there is often already a check for if the service is alive such as `check-redis-ping.rb` rather than sending a crit on all of them I actually like using unknown for connection issues when its goal is not to ascertain if the service is alive and to offer an option to modify this with something like `--fail-on-connection-issues`. I realize that some of this can obviously be handled with check dependencies but that is a feature I have seen very few people actually use properly if at all. I don't find any value in having checks that expect a service to be to be concerned about alerting that the dependent service is alive. Otherwise every check takes on the responsibility of the alive check which if that is the case the alive checks should be removed.

**Comment by majormoses** [comment]
closing due to inactivity.

**Pull request closed without merging**
