### PR TITLE
fix variable interpolation, using double quotes

### PR DESCRIPTION
**Pull request by zerOnepal**
## this is a just a fix
**Is this in reference to an existing issue?**
Yes,  addressing #14 
with regard to the silly mistake i made,
ruby_variable_dont_expand_inside_single_quotes
 
#### Purpose
Since variables inside the single quotes don't expand so
 output when ok used to yeild something like this:

cf_sing_quotes_discuss_monitoringlove

### CODE REVIEW

**Comment by BrotherCheng** [comment]
@zerOnepal , thanks for this fix.  For now, the output just contains a number, Could we make the output msg more clearer? 
For example, 135MB, 2.5G in [check-redis-memory.rb](https://github.com/sensu-plugins/sensu-plugins-redis/blob/master/bin/check-redis-memory.rb#L68)
25%, 70% in [check-redis-memory-percentage.rb](https://github.com/sensu-plugins/sensu-plugins-redis/blob/master/bin/check-redis-memory-percentage.rb#L89)

**Comment by willneumob** [comment]
nit: The '%' should not have a space before it. This needs to be merged asaply, though :)

**Comment by sstarcher** [comment]
@zerOnepal can you rebase this

**Comment by eheydrick** [comment]
Merged manually. Fixes #14.

**Comment by zerOnepal** [comment]
@sstarcher @eheydrick thanks guyz :bow: 
...applogies, can't made it, I was over the hills.

**Pull request closed without merging**
