### PR TITLE
Feature/add timeout option

### PR DESCRIPTION
**Pull request by empyrean987**
please review

### CODE REVIEW

**Comment by empyrean987** [comment]
Do you have an example of a gist file with what you are requesting?

**Comment by majormoses** [comment]
here is an example: https://github.com/sensu-plugins/sensu-plugins-aws/pull/231 you can put it directly on the PR if there is not a ton of output.

**Comment by empyrean987** [comment]
Here is an example of executing the ping & info commands on how to use the timeout functionality. 
#./check_redis_ping_timeout.rb -h localhost -t 15
RedisPing OK: Redis is alive
#./check_redis_info_timeout.rb -h localhost -t 15
RedisSlaveCheck OK: Redis role is master

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-redis/versions/2.2.0

**Pull request merged**
